### ISSUE TITLE
豆瓣把tag关了，页面里找了个内容不知道能不能替代

### ISSUE THREAD

**Issue by herobst** [fugary/calibre-douban#3]
![image](https://user-images.githubusercontent.com/17536563/157410579-5713e15d-5a2e-4b48-b2b8-8894a717dfb6.png)

**Comment by fugary** [comment]
这个好像没办法了，因为“豆瓣标签事件”，官方把标签显示移除了，应该也没有打标签功能了

**Comment by herobst** [comment]
1.还是有标签的，截图里面内容属于这本书的大标签，文学作品/计算机科学
![image](https://user-images.githubusercontent.com/17536563/157599537-da737fbf-91f5-409c-af10-82d3d29460e8.png)
2.还有一个问题就是出版社现在获取失效了，不知道什么原因

**Comment by fugary** [comment]
出版社获取失败问题已修复

**Comment by fugary** [comment]
tags已经添加
