### ISSUE TITLE
书籍标签

### ISSUE THREAD

**Issue by Cheukfung** [fugary/calibre-douban#4]
cxfksword/douban-api-rs 这个项目是可以获取书籍的tag的，请问能不能加上书籍标签的功能呢

**Comment by fugary** [comment]
douban官网把tag关闭了，页面上都没有，没法获取tag，douban-api-rs应该也不会有吧

**Comment by Cheukfung** [comment]
感谢作者的工作。
我是用talebook/talebook来管理，他调用了douban-api-rs来更新书籍，可以更新标签，我就以为是能获取tag。后来测试了dou ban-api-rs的确无法获取tag。
最后查看talebook的源码发现，是通过匹配固定标签和简介里面的内容来实现的，虽然不会很准确，但不失为一种方法。
` if len(refer_mi.tags) == 0 and len(mi.tags) == 0:
                ts = []
                for nn, tags in constants.BOOKNAV:
                    for tag in tags:
                        if tag in refer_mi.title or tag in refer_mi.comments:
                            ts.append(tag)
                        elif tag in refer_mi.authors:
                            ts.append(tag)
                if len(ts) > 0:
                    mi.tags += ts[:8]
                    logging.info("tags are %s" % ','.join(mi.tags))
                    self.db.set_tags(book_id, mi.tags)
            mi.smart_update(refer_mi, replace_metadata=True)
`

**Comment by fugary** [comment]
用描述或者标题关键字判断tag，很容易误判，有空试试看

**Comment by Cheukfung** [comment]
昨天提了pr了，你可以看看

**Comment by fugary** [comment]
源文件中的criteria作为标签似乎更合适：
criteria = '7:计算机|7:计算机科学|7:计算机系统|7:计算机体系结构|7:操作系统|7:CSAPP|7:计算机底层|7:编程|7:CS|7:经典|3:/subject/26912767/',
