### ISSUE TITLE
元数据乱下书

### ISSUE THREAD

**Issue by BlackArknight** [fugary/calibre-douban#6]
下载元数据总是下载成另一本书
![E2_J~LI)(K(UOL9$_9T206H](https://user-images.githubusercontent.com/58136772/168201386-3570c896-e98d-4f33-8edb-572e4bc61071.png)

**Comment by fugary** [comment]
估计是因为ids里面已经有isbn号的话，优先用isbn号查询的，可以先删掉ids里面的内容

**Comment by BlackArknight** [comment]
已经解决
